AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Resources to be created by the common stack"

Resources:
  ######## KMS #########
  rKMSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stack/template-kms.yaml

  ######## DYNAMODB #########
  rDynamoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stack/template-ddb.yaml
      Parameters:
        pKMSKeyId: !GetAtt [ "rKMSStack", "Outputs.oKMSKeyId" ]

  ######## SNS Fanout #########
  rWLM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stack/template-workload-management.yaml
      Parameters:
        pKMSKeyId: !GetAtt [ "rKMSStack", "Outputs.oKMSKeyId" ]
        pSNSNotificationsEmail: xyz@amazon.com
        pddb: !GetAtt [ "rDynamoStack", "Outputs.oddb" ]
      

  

  